### ISSUE TITLE
09-rogueliketutorial-05 missing call to `set_entity_type` within entity.gd `_init` function.

### ISSUE THREAD

**Issue by efredericks** [SelinaDev/SelinaDev.github.io#1]
I was receiving a null reference error every time I tried to move around after finishing 09-rogueliketutorial-05 and there would be a `Invalid get index 'is_blocking_movement' (on base: 'Nil')` error.

Not sure if this is me overlooking something, but a mention to update the `_init` function within entity.gd could be useful:

```
func _init(start_position: Vector2i, entity_definition: EntityDefinition) -> void:
	centered = false
	grid_position = start_position
	set_entity_type(entity_definition)
```

I basically just did a compare with the GH codebase to see what I was missing in the text post and noticed this.  I can submit a PR for an `index.html` update if you'd like (I wasn't sure if you were using a local jekyll tool for building the site or not).

**Comment by SelinaDev** [comment]
Thank you for alerting me to this. I added a mention to that in that tutorial part now and uploaded it.
(I am in fact building the site from a private repository using hugo)
