### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by icefoxen** [SelinaDev/SelinaDev.github.io#3]
Here: https://github.com/SelinaDev/SelinaDev.github.io/blob/31c54e2c312bf253c88328bc7eac275ccc35cae3/05-rogueliketutorial-01/index.html#L91

Needs a https:// to not be treated as a relative link. Sorry for no PR, I'm on my phone.

**Comment by SelinaDev** [comment]
Hi! Thank you for mentioning that. You mean the link to rogueliketutorials.com, right? Just fixed it, should be up on the live version of the site shortly.
